@startuml
'https://plantuml.com/class-diagram
ToDoList*-ToDoItem
ListCollection*-ToDoList
javafx.Application<|-- ListCollection
Controller-- ListCollection

class Controller{
}
class ListCollection{
    lists : ArrayList<ToDoList>

    addList()
    removeList()
    saveAllToFile()
    readMultipleFromFile()
    findListSpot()
}

class ToDoList{
    title : String
    items : ArrayList<ToDoItem>

    setTitle()
    getTitle()
    getItems()
    addItem()
    removeItem()
    displayCompleteness()
    saveToFile()
    readFromFile()
    sortList()
    findItemSpot()
}

class ToDoItem{
    completed : boolean
    description : String
    dueDate : String

    getCompleted()
    setCompleted()
    getDescription()
    setDescription()
    getDueDate()
    setDueDate()
    displayInfo()
    confirmFormat()
}

@enduml