@startuml
'https://plantuml.com/class-diagram
ToDoList*-ToDoItem
javafx.Application<|-- Controller
Controller-- ToDoList
ToDoItem<|- Date
Controller <|- App
class Controller{
titleName : TextField
addDesc : TextField
addDate : TextField
editOrigDesc : TextField
editNewDesc : TextField
editDate : TextField
addComplete : CheckBox
editComplete : CheckBox
displayArea : TextArea
list : ToDoList

removeItem()
displaySort()
editItem()
addItem()
clearAllItems()
displayIncomplete()
displayComplete()
displayAll()
setTitle()
saveToFile()
loadFromFile()
upadtingDescription()
}
class App{
start()
}
class ToDoList{
    title : String
    items : ArrayList<ToDoItem>
    numItems : int
    fileRead : boolean

    getFileRead()
    getNumItems()
    setTitle()
    getTitle()
    getItems()
    addItem()
    removeItem()
    displayAll()
    displayCompleteness()
    saveToFile()
    readFromFile()
    sortList()
    findItemSpot()
    displayInfo()
    editArrayItem()
    returnArraySpotDescription()
    returnArraySpotDueDate()
    returnArraySpotCompleted()
}

class ToDoItem{
    completed : boolean
    description : String
    dueDate : Date

    getCompleted()
    setCompleted()
    getDescription()
    setDescription()
    getDueDate()
    setDueDate()
    displayInfo()

}

class Date{
    date : String
    day: int
    month : int
    year : int
    getDate()
    setDate()
    confirmValidDate()
}
@enduml