@startuml
'https://plantuml.com/class-diagram
ToDoList*-ToDoItem
ListCollection*-ToDoList
javafx.Application<|-- Controller
Controller-- ListCollection

class Controller{

    String existingDescription;
    String existingDueDate;
    String listTitle;
    String originalDescription;
    String display;
    boolean existingCompleted;
    String newDescription;
    String newDueDate;
    boolean newCompleted;

    loadListClicked()
    newListClicked()
    loadAllClicked()
    loadListFile()
    editListClicked()
    editGivenList()
    removeList()
    saveList()
    saveAllLists()
    displayAll()
    displayCompleted()
    displayIncomplete()
    stopEditing()
    removeItem()
    addItem()
    editClicked()
    editTitle()

}
class ListCollection{
    lists : ArrayList<ToDoList>

    addList()
    removeList()
    saveAllToFile()
    readMultipleFromFile()
    findListSpot()
}

class ToDoList{
    title : String
    items : ArrayList<ToDoItem>

    setTitle()
    getTitle()
    getItems()
    addItem()
    removeItem()
    displayCompleteness()
    saveToFile()
    readFromFile()
    sortList()
    findItemSpot()
    displayAll()
}

class ToDoItem{
    completed : boolean
    description : String
    dueDate : String

    getCompleted()
    setCompleted()
    getDescription()
    setDescription()
    getDueDate()
    setDueDate()
    displayInfo()
    confirmFormat()
}

@enduml